name: "Blender GLE"

exports: "blender-gle.coffee"

web: ""

description: ""

license: ""

copyright: ""

authors: ""

sources:
  - "Source/Core/Core.Checkbox.coffee"
  - "Source/Core/Core.Icon.coffee"
  - "Source/Groups/Core.IconGroup.coffee"
  - "Source/Core/Core.Tip.coffee"
  - "Source/Core/Core.Slider.coffee"
  - "Source/Core/Core.Scrollbar.coffee"
  - "Source/Buttons/Buttons.Abstract.coffee"
  - "Source/Buttons/Buttons.Key.coffee"
  - "Source/Core/Core.Picker.coffee"
  - "Source/Core/Core.Slot.coffee"
  - "Source/Core/Core.Toggler.coffee"
  - "Source/Core/Core.Overlay.coffee"
  - "Source/Core/Core.Tab.coffee"
  - "Source/Groups/Core.Tabs.coffee"
  - "Source/Buttons/Buttons.Toggle.coffee"
  - "Source/Groups/Core.PushGroup.coffee"
  - "Source/Data/Data.Select.coffee"
  - "Source/Data/Data.Text.coffee"
  - "Source/Data/Data.Number.coffee"
  - "Source/Data/Data.Color.coffee"
  - "Source/Data/Data.ColorWheel.coffee"
  - "Source/Data/Data.DateTime.coffee"
  - "Source/Data/Data.Table.coffee"
  - "Source/Data/Data.Unit.coffee"
  - "Source/Data/Data.List.coffee"
  - "Source/Dialog/Dialog.Prompt.coffee"
  - "Source/Iterable/Iterable.ListItem.coffee"
  - "Source/Iterable/Iterable.List.coffee"
  - "Source/Layout/Layout.coffee"
  - "Source/Layout/Corner.coffee"
  - "Source/Layout/Toolbar.coffee"
  - "Source/Layout/View.coffee"
  - "Source/Pickers/Pickers.coffee"
