GDotUI.Theme={
    css:'theme.css',
    iconClass:'icon',
    tipClass:'tip',
    button:{
      'class':'button',
      width: 200
    },
    List:{
      'class':'list'  
    },
    Float:{
        'class':'float',
        bottomHandleClass:'bottom',
        handleClass:'handle',
        closeClass:'close',
        baseClass:'base',
        editClass:'edit',
        iconsClass:'controls',
        iconOptions:{
            mode:'vertical',
            spacing:{
                x:0,
                y:3
            }
        }
    },
    ListItem:{
      'class':'list-item',
      title:'title',
      subTitle:'subtitle',
      iconOffset:2
    },
    Icons:{
      remove:'../Themes/Blank/images/delete.png',
      handleVertical:'../Themes/Blank/images/control_pause.png',
      handleHorizontal:''
    },
    Color:{
       //saturation and brightness field
       sb:'sb',
       hue:'hue',
       black:'black',
       white:'white',
       color:'color',
       wrapper:'wrapper',
      'class':'color',
       controls:{
          'class':'control',
          format:'format',
          colorBox:'colorBox'
       }
    },
    Slider:{
        barClass:'bar',
        knobClass:'knob',
        length: 80,
        width: 12
    }
}